apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-axiom
spec:
  selector:
    app: axiom
  ports:
    - port: {{ .Values.apiPort }}
      targetPort: http
      name: http
    - port: {{ .Values.gossipPort }}
      targetPort: gossip
      name: gossip
